import menuResponsive from "./assets/icons/menu-responsive.png";
import arrowDoor from "./assets/icons/arrow-door.png";
import search from "./assets/icons/search.png";
import logo from "./assets/icons/logo.png";
import localFont from "next/font/local";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "iPractis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <nav className="container-page px-3 py-3">
          <div className="flex justify-between items-center gap-4">
            <div>
              <Link href={"/"}>
                <Image
                  alt="Logo Image"
                  className="w-32 inline-block"
                  src={logo}
                />
              </Link>
            </div>

            <div className="relative sm:block hidden">
              <input
                className="placeholder-black outline-none font-bold px-8"
                placeholder="Find a tutor"
                type="text"
              />
              <Image
                className="absolute left-0 inline-block w-6"
                alt="Logo Search"
                src={search}
              />
            </div>

            <div className="space-x-6 sm:block hidden">
              <Link className="font-bold" href={"#"}>
                Become a tutor
              </Link>

              <Link className="font-bold" href={"/login"}>
                Log in{" "}
                <Image
                  alt="Arrow Door"
                  className="inline-block w-6"
                  src={arrowDoor}
                />
              </Link>

              <Link href={"/register"}>
                <button type="button" className="btn btn-black w-auto">
                  Register
                </button>
              </Link>
            </div>

            <div className="sm:hidden block">
              <Image
                alt="Menu Responsive Logo"
                className="w-12 inline-block cursor-pointer"
                src={menuResponsive}
              />
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
