import { Providers } from "@/contextProviders/Providers";
import Navbar from "./rootComponents/Navbar";
import "./globals.css";

export const metadata = {
  title: "iPractis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased overflow-x-hidden`}
        suppressHydrationWarning={true}
      >
        <Providers>
          <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
